language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
before_script:
  - composer install --prefer-source --no-interaction
  - cp config/config.sample.php config/config.php
  - mysql -e 'create database sample_database;'
script:
  - vendor/bin/phpunit